#!/bin/sh

# args::
ASD_TARGET="none"
ASD_GIT_BRANCH="_asd_" 
ASD_DELAY=900
ASD_RUN_ROOT=$PWD
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 14)
YELLOW=$(tput setaf 3)
GRAY=$(tput setaf 244)
RED=$(tput setaf 9)
NORMAL=$(tput sgr0)

while [ $# -gt 0 ]
do
    arg="$1"
    case $arg in 
        -t|--target)
            ASD_TARGET="$2"
            shift;;
        -b|--branch)
            ASD_GIT_BRANCH="$2"
            shift;;
        -d|--delay)
            ASD_DELAY="$2"
            shift;;
        -h|--help)
            echo "[autosaved]::git autocommit daemon\n"
            echo "Automatically stage and commits change to '_asd_' branch every 15 minutes"
            echo "Usage: autosaved.sh --target DIRECTORY [--branch BRANCH] [--delay DELAY]"
            echo "  --target  ASD_TARGET  Required. Spcify directory to watch for git repo(s), recursively."
            echo "  --branch  ASD_BRANCH  Optional. Default value '_asd_'. Specify git branch to commit changes."
            echo "  --delay   ASD_DELAY   Optional. Default value '900'. Specify thread sleep delay."
            exit 0;;
        *)
            printf "[autosaved]::unknown_arg::$1"
            exit 1;;
    esac
    shift
done

# check::arg::dir
if [ ! -d "${ASD_TARGET}" ]; then
    printf "ERROR: ${ASD_TARGET} does not exist or is not a directory \n"
    exit 1;
fi

# thread::
while true; do
    printf "${GRAY}[autosaved->$(date +%s)]::${GREEN}[diff->dir]::${CYAN}${ASD_TARGET}\n"
    # cd ${ASD_TARGET}

    # find::.git::repositories
    for dir in $(find $ASD_TARGET -type d -name .git); do
        echo "cd::${dir%.git}"
        cd "$(dirname "${dir%.git}")"

        # check::git_status
        if ! git diff-index --quiet HEAD --; then
            # stage::changes::
            git add .
            printf "${GRAY}[autosaved->$(date +%s)]::${RED}[git_stage]::${CYAN}$(pwd)${YELLOW}\n"

            if ! git show-ref refs/heads/_asd &> /dev/null; then
                git branch ${ASD_GIT_BRANCH}
                printf "${GRAY}[autosaved->$(date +%s)]::${RED}[git_branch->${ASD_GIT_BRANCH}]::${CYAN}$(pwd)${YELLOW}\n"
            fi

            # commit::
            GIT_MOD_C=$(git diff --numstat HEAD | wc -l)
            git commit -m "auto:: ${GIT_MOD_C} files modified"

            printf "${GRAY}[autosaved->$(date +%s)]::${RED}[git_commit->${GIT_MOD_C}]::${CYAN}$(pwd)\n"
        fi

        cd "${ASD_RUN_ROOT}"
    done

    printf "${GRAY}[autosaved->$(date +%s)]::${GREEN}[thread_sleep->${ASD_DELAY}]${NORMAL}\n"
    sleep ${ASD_DELAY}
done

set +x;
